server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_microservice?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wxhdszz...
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml
